### ISSUE TITLE
Theme-Mode is not defined

### ISSUE THREAD

**Issue by nbfields** [emacs-eaf/eaf-jupyter#3]
EAF buffer information:
```Traceback (most recent call last):
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 170, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 187, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/jupyter/buffer.py", line 41, in __init__
    self.add_widget(EafJupyterWidget(self.kernel,
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/app/jupyter/buffer.py", line 69, in __init__
    (jupyter_dark_mode == "follow" and theme_mode == "dark"))
NameError: name 'theme_mode' is not defined
Traceback (most recent call last):
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 250, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '6ee6-a5d2-dc00-6547-dc49-411b-c986'
Traceback (most recent call last):
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/nbfields/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 250, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '6ee6-a5d2-dc00-6547-dc49-411b-c986'
```

**Describe the bug**
Attempting to open the eaf Jupyter plugin results in the above error output and no opening of jupyter-qtconsole in or out of Emacs.

**To Reproduce**
type `M-x eaf-open-jupyter` followed by the python3 kernel.

**Expected behavior**

Jupyter would open and provide no error.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 20.04.3 LTS
 - Versions of Dependencies: qtconsole 5.2.0
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-11-04

**Additional context**

I don't doubt that this is a mistake on my end and not an actual bug in EAF or any of its packages, but I also don't know how to resolve it.

**Comment by manateelazycat** [comment]
@nbfields Newest version has fix this issue, thanks for report. ;)
